[package]
name = "autonexus-hw"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
autonexus-common = { version = "0.1.0", path = "../autonexus-common" }
tokio = { version = "1.49.0", features = ["full"] }
