[package]
name = "autonexus-protocols"
version = "0.1.0"
edition = "2024"

[dependencies]
autonexus-common = { version = "0.1.0", path = "../autonexus-common" }
autonexus-hw = { version = "0.1.0", path = "../autonexus-hw" }
